### PR TITLE
fix(resolver): extract $value from nested resolvables

### LINKED ISSUE #102: Nested resolvables resolve to JSON object string instead of actual value
### What problem does this solve?

When a resource property references another resource's property that is itself a $ref (nested resolvables), formae incorrectly resolves to the JSON string of the $ref object instead of the actual value.

This causes false positive replace operations because the resolved value doesn't match the expected format. AWS doesn't exhibit this issue because its resource hierarchy doesn't nest resolvables beyond two levels.

### Proposed solution

When extracting a property value for resolution, check if the value is a `$ref` object and extract the `$value` from within it

### PR DESCRIPTION
**Pull request by browdues**
Solves cases when a resource property references another resource's property that is itself a `$ref`

Example: In OCI, a Subnet references a VCN's `CompartmentId`, which itself references a Compartment's `Id`:

```text
Subnet.CompartmentId -> VCN.CompartmentId -> Compartment.Id
```
In applicable cases,  this causes false positive replace operations because the resolved value doesn't match the expected format. AWS doesn't exhibit this issue because its resource hierarchy doesn't nest resolvables beyond two levels.

Closes #102

### CODE REVIEW

File: internal/metastructure/resolver/resolver_test.go [hunk 1]
```diff
@@ -992,6 +992,180 @@ func TestResolveMultiplePropertiesSameResolverInstance(t *testing.T) {
...
+
+		// VCN's CompartmentId is a $ref pointing to the Compartment's Id
+		// This is the nested resolvable scenario
+		vcn := pkgmodel.Resource{
+			Ksuid: vcnKsuid,
+			Label: "vcn",
+			Properties: json.RawMessage(fmt.Sprintf(`{
+				"CompartmentId": {
+					"$ref": "formae://%s#/Id",
+					"$value": "ocid1.compartment.oc1..abc123"
```
Comment (JeroenSoeters) [inline internal/metastructure/resolver/resolver_test.go:1050]: What would happen if this property is not yet resolved and does not have a `$value` or is it guaranteed to always have one at this point?

File: internal/metastructure/changeset/resolve_cache.go [hunk 2]
```diff
@@ -139,14 +140,14 @@ func (r *ResolveCache) resolveValue(resourceURI pkgmodel.FormaeURI) (string, err
...
-	r.Log().Debug("Cache hit for resource URI", "uri", resourceURI, "value", enhancedParsed)
+	r.Log().Debug("Cached resource properties", "uri", resourceURI, "value", enhancedParsed)
 	value := enhancedParsed.Get(resourceURI.PropertyPath())
 	if !value.Exists() {
 		r.Log().Error("Unable to resolve property %s in cached properties for resource %s", resourceURI.PropertyPath(), resourceURI)
 		return "", fmt.Errorf("property %s not found in cached properties for resource %s", resourceURI.PropertyPath(), resourceURI)
 	}
 
-	return value.String(), nil
+	return resolver.ExtractPropertyValue(value), nil
```
Comment (JeroenSoeters) [inline internal/metastructure/changeset/resolve_cache.go]: The responsibility of the `ResolveCache` is to do just-in-time resolving to make sure that when changes have happened outside of the tool, we pick them up. In this implementation we are not refreshing the value of the nested resolvable. In other words, in the `Subnet` -> `VCN` -> `Compartment` example, if someone would have assigned the `VCN` to a different compartment outside of the tool, we would miss this change.

What we should do instead, is recursively issue reads for nested resources. Similarly to how we fetch the `VCN` when we try to resolve the property on the `Subnet`, we should fetch the `Compartment` when we try to resolve the property on the `VCN`.

File: internal/metastructure/changeset/resolve_cache.go [hunk 3]
```diff
@@ -139,14 +140,14 @@ func (r *ResolveCache) resolveValue(resourceURI pkgmodel.FormaeURI) (string, err
 	enhancedParsed := r.preserveRefMetadata(loadResourceResult.Resource, parsed)
 
 	r.cache[resourceURI.Stripped()] = enhancedParsed
-	r.Log().Debug("Cache hit for resource URI", "uri", resourceURI, "value", enhancedParsed)
+	r.Log().Debug("Cached resource properties", "uri", resourceURI, "value", enhancedParsed)
```
Comment (naxty) [inline internal/metastructure/changeset/resolve_cache.go]: Just saw this renaming and was wondering a bit if we then should rename line 76 as well that has "Cache hit ..." in it.

File: internal/metastructure/resolver/resolver_test.go (hunk 1 above)
Comment (browdues) [reply internal/metastructure/resolver/resolver_test.go:1050]: For creates, the dependency ordering ensures parent resources are processed first, so their values should exist. For patch documents (updates), referenced resources should already have values from prior sync/discovery

File: internal/metastructure/changeset/resolve_cache.go (hunk 3 above)
Comment (browdues) [reply internal/metastructure/changeset/resolve_cache.go]: Moved back to original message.
