### PR TITLE
fix: validation of fields in resource_persister was incorrectly triggered

### LINKED ISSUE #92: Deletion of certain resources in the cloud does not get reflected in the metastructure
### Version

```markdown
formae version: 0.75.1
go version: go1.25.1
```

### Formae configuration

```markdown
n/a
```

### Steps to reproduce

```markdown
1. Run the lifeline example
2. Manually delete a Subnet in the AWS console
```

### Actual behavior

```markdown
When running the inventory command the Subnet would not get removed from the inventory
```

### Expected behavior

```markdown
I would expect the Subnet to be removed, similar to when I delete an InternetGateway
```

### Logs/output

```markdown
2025-11-21T09:56:42-05:00 ERR Validation of required fields failed error="resource hello of type AWS::EC2::Subnet is missing required fields: [Tags]"
```

### Additional context

_No response_

### Impact

Medium - Partial functionality affected

### PR DESCRIPTION
**Pull request by JeroenSoeters**
We need to infer the correct resource operation based in the `ProgressResult`. When we get a `ProgressResult` with a `Success` response **and** an `ErrorCode` `NotFound`, we treat the operation as a delete. 

The validation logic was guarded by a check for `OperationDelete`, however, this was before the operation was translated. Iow the operation was still `OperationRead` and we would incorrectly trigger validation logic causing certain deletes to fail.

Closes #92

### CODE REVIEW

File: internal/metastructure/resource_persister/resource_persister.go [hunk 1]
```diff
@@ -79,18 +79,18 @@ func (rp *ResourcePersister) storeResourceUpdate(commandID string, resourceOpera
...
+	resourceUpdate.Operation = resourceOperationFromPluginOperation(resourceOperation, pluginOperation, relevantProgress)
+
 	// This can cause a validation error when the delete op is in fact valid.
 	// Subsequently no delete is persisted and the system doesn't work as expected.
 	// To avoid this, we skip the validation when the operation is a delete.
-	if resourceOperation != resource_update.OperationDelete {
+	if resourceUpdate.Operation != resource_update.OperationDelete {
 		if err := validateRequiredFields(resourceUpdate.Resource); err != nil {
 			slog.Debug("Validation of required fields failed", "error", err)
 			return "", nil
```
Comment (browdues) [inline internal/metastructure/resource_persister/resource_persister.go:90]: Should we return after the validation err? Seems like we should log and continue, as this is likely a schema issue and not a problem with data integrity (since we're storing what AWS has relayed from the request)

Comment (JeroenSoeters) [reply internal/metastructure/resource_persister/resource_persister.go:90]: We do return after the error?

**Review by browdues — APPROVED** [review]
